<?php
//$this->headScript()->appendFile( '/assets/layout/js/jquery.nanoscroller/jquery.nanoscroller.js');
?>
<?php
$services = array(
    array("id" => 1,
        "label" => "L1",
        "childList" => array(
            array(
                "id" => 2,
                "label" => "L1-1",
                "childList" => array()
            ),
            array(
                "id" => 3,
                "label" => "L1-2",
                "childList" => array()
            )
        )
    ),
    array("id" => 4,
        "label" => "L2",
        "childList" => array(
            array(
                "id" => 5,
                "label" => "L2-1",
                "childList" => array(
                    array(
                        "id" => 6,
                        "label" => "L2-1-1",
                        "childList" => array()
                    )
                )
            )
        )
    )
        )
?>
<?php echo $this->partial('partial/tree-select-partial.phtml', array($services)); ?>



<div class="title">
    <h2>Tree View</h2>
</div>
<ul class="nav nav-list treeview">
    <li class=""><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> General</label>
        <ul class="nav nav-list tree" style="display: none;">
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Structure</label>
                <ul class="nav nav-list tree">
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                    <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Plugins</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
    <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Documentation</label>
        <ul class="nav nav-list tree">
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Components</label>
                <ul class="nav nav-list tree">
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                    <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Speech API</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Charts</label>
                <ul class="nav nav-list tree">
                    <li><a href="#">Link</a></li>
                    <li><a href="#">Link</a></li>
                    <li><label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i> Reports</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Link</a></li>
                            <li><a href="#">Link</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>
