<?php
//$this->headScript()->appendFile( '/assets/layout/js/jquery.nanoscroller/jquery.nanoscroller.js');
?>



<?php if(isset($title)):?>
<div class="title">
    <h2><?=$title?></h2>
</div>
<?php endif;?>
<?php if(count($services)>0):?>
    <ul class="nav nav-list tree<?=(!isset($notFirst))?"view":""?>">
        <?php foreach($services as $service):?>
            <li>
                <?php if(count($service["childList"])>0):?>
                    <label class="tree-toggler nav-header" id="<?=$service["id"]?>"><i class="fa fa-folder-o"></i> <?=$service["label"]?></label>
                    <?php echo $this->partial('ui/form/element/tree-select', array("services"=>$service["childList"],"notFirst"=>1)); ?>
                <?php else:?>
                    <a href="#" id="<?=$service["id"]?>"><?=$service["label"]?></a>
                <?php endif;?>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif;?>

<?php if (!isset($notFirst)):?>
<input type="text" name="<?=$name?>" style="display: none;" value="16">
<?php endif;?>
