<?php foreach ($services as $service => $value): ?>
    <ul class="nav nav-list treeview">
        <li class="" id="<?= $value['id'] ?>">
            <label class="tree-toggler nav-header"><i class="fa fa-folder-o"></i><?= $value['label'] ?></label>
                <?php if (is_array($value['childList'])): ?>
                    <?php echo $this->partial('partial/tree-select-partial.phtml', array($value['childList'])); ?>
                <?php endif; ?> 
        </li>
    </ul>
<?php endforeach; ?>