<div class="col-sm-6 col-md-12">
    <div class="block-flat">
        <div class="header">
            <h3><?php echo $header  ?></h3>
        </div>
        <div class="content">
            <form method="<?php echo 'POST'?>"  action="<?= $action ?>" class="form-horizontal group-border-dashed" role="form" enctype="multipart/form-data">
                <?php foreach($this->viewModel()->getCurrent()->getChildren() as $child) : ?>
                    <?php echo $child->render()  ?>
                <?php endforeach ?>
            </form>
        </div>
    </div>
</div>
