<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/icon.png">

    <title>Flat Dream</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,200,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <?php echo $this->headLink()
        ->appendStylesheet($this->basePath() . '/assets/layout/js/bootstrap/dist/css/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.gritter/css/jquery.gritter.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/fonts/font-awesome-4/css/font-awesome.min.css');

        $this->headLink()->deleteContainer();

    ?>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php
        echo $this->headScript()->prependFile($this->basePath() . '/assets/layout/../../assets/js/html5shiv.js')
                                ->prependFile($this->basePath() . '/assets/layout/../../assets/js/respond.min.js');
    ?>
    <![endif]-->
    <?php echo $this->headLink()
        ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.nanoscroller/nanoscroller.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.codemirror/lib/codemirror.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.codemirror/theme/ambiance.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/js/jquery.vectormaps/jquery-jvectormap-1.2.2.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/js/dropzone/css/dropzone.css')
        ->appendStylesheet($this->basePath() . '/assets/layout/css/style.css');
        $this->headLink()->deleteContainer();
    ?>
</head>
<body>

<div id="cl-wrapper">

    <div class="cl-sidebar">
        <div class="cl-toggle"><i class="fa fa-bars"></i></div>
        <div class="cl-navblock">
            <div class="menu-space">
                <div class="content">
                    <div class="sidebar-logo">
                        <div class="logo">
                            <a href="index2.html"></a>
                        </div>
                    </div>
                    <div class="side-user">
                        <div class="avatar"><img src="assets/layout/images/avatar6.jpg" alt="Avatar" /></div>
                        <div class="info">
                            <p>40 <b>GB</b> / 100 <b>GB</b><span><a href="#"><i class="fa fa-plus"></i></a></span></p>
                            <div class="progress progress-user">
                                <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    <span class="sr-only">50% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <ul class="cl-vnavigation">
                        <li class="active" ><a href="index-2.html"><i class="fa fa-home"></i><span>Dashboard</span></a></li>
                        <li><a href="#"><i class="fa fa-smile-o"></i><span>UI Elements</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="ui-elements.html">General</a></li>
                                <li  ><a href="ui-alerts.html">Alerts</a></li>
                                <li  ><a href="ui-porlets.html">Porlets</a></li>
                                <li  ><a href="ui-buttons.html">Buttons</a></li>
                                <li  ><a href="ui-modals.html">Modals</a></li>
                                <li  ><a href="ui-notifications.html">Notifications</a></li>
                                <li  ><a href="ui-tiles.html">Tiles</a></li>
                                <li  ><a href="ui-progress.html">Progress Bars</a></li>
                                <li  ><a href="ui-icons.html">Icons</a></li>
                                <li  ><a href="ui-grid.html">Grid</a></li>
                                <li  ><a href="ui-tabs-accordions.html">Tabs & Accordions</a></li>
                                <li  ><a href="ui-nestable-lists.html">Nestable Lists</a></li>
                                <li  ><a href="ui-treeview.html">Tree View</a></li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-list-alt"></i><span>Forms</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="form-elements.html">Components</a></li>
                                <li  ><a href="form-validation.html">Validation</a></li>
                                <li  ><a href="form-wizard.html">Wizard</a></li>
                                <li  ><a href="form-masks.html">Input Masks</a></li>
                                <li  ><a href="form-wysiwyg.html">WYSIWYG Editor</a></li>
                                <li  ><a href="form-upload.html">Multi Upload</a></li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-table"></i><span>Tables</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="tables-general.html">General</a></li>
                                <li  ><a href="tables-datatables.html">Data Tables</a></li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-map-marker nav-icon"></i><span>Maps</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="maps.html">Maps</a></li>
                                <li  ><a href="vector-maps.html">Vector Maps</a></li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-envelope nav-icon"></i><span>Email</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="email-inbox.html">Inbox</a></li>
                                <li  ><a href="email-read.html">Email Detail</a></li>
                            </ul>
                        </li>
                        <li  ><a href="typography.html"><i class="fa fa-text-height"></i><span>Typography</span></a></li>
                        <li  ><a href="charts.html"><i class="fa fa-bar-chart-o"></i><span>Charts</span></a></li>
                        <li><a href="#"><i class="fa fa-file"></i><span>Pages</span></a>
                            <ul class="sub-menu">
                                <li  ><a href="pages-blank.html">Blank Page</a></li>
                                <li  ><a href="pages-blank-header.html">Blank Page Header</a></li>
                                <li  ><a href="pages-blank-aside.html">Blank Page Aside</a></li>
                                <li><a href="pages-login.html">Login</a></li>
                                <li><a href="pages-404.html">404 Page</a></li>
                                <li><a href="pages-500.html">500 Page</a></li>
                                <li  ><a href="pages-gallery.html">Gallery</a></li>
                                <li  ><a href="pages-timeline.html">Timeline</a></li>
                                <li  ><a href="pages-code-editor.html">Code Editor</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="text-right collapse-button" style="padding:7px 9px;">
                <input type="text" class="form-control search" placeholder="Search..." />
                <button id="sidebar-collapse" class="btn btn-default" style=""><i style="color:#fff;" class="fa fa-angle-left"></i></button>
            </div>
        </div>
    </div>
    <div class="container-fluid" id="pcont">
        <!-- TOP NAVBAR -->
        <div id="head-nav" class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-collapse">
                    <ul class="nav navbar-nav navbar-right user-nav">
                        <li class="dropdown profile_menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img alt="Avatar" src="assets/layout/images/avatar6-2.jpg" /><span>Jane Smith</span> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">Profile</a></li>
                                <li><a href="#">Messages</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Sign Out</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav not-nav">
                        <li class="button dropdown">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class=" fa fa-inbox"></i></a>
                            <ul class="dropdown-menu messages">
                                <li>
                                    <div class="nano nscroller">
                                        <div class="content">
                                            <ul>
                                                <li>
                                                    <a href="#">
                                                        <img src="assets/layout/images/avatar2.jpg" alt="avatar" /><span class="date pull-right">13 Sept.</span> <span class="name">Daniel</span> Hey! How are you?
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <img src="assets/layout/images/avatar_50.jpg" alt="avatar" /><span class="date pull-right">20 Oct.</span><span class="name">Adam</span> Hi! Can you fix my phone?
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <img src="assets/layout/images/avatar4_50.jpg" alt="avatar" /><span class="date pull-right">2 Nov.</span><span class="name">Michael</span> Regards!
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#">
                                                        <img src="assets/layout/images/avatar3_50.jpg" alt="avatar" /><span class="date pull-right">2 Nov.</span><span class="name">Lucy</span> Hello, my name is Lucy
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <ul class="foot"><li><a href="#">View all messages </a></li></ul>
                                </li>
                            </ul>
                        </li>
                        <li class="button dropdown">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe"></i><span class="bubble">2</span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="nano nscroller">
                                        <div class="content">
                                            <ul>
                                                <li><a href="#"><i class="fa fa-cloud-upload info"></i><b>Daniel</b> is now following you <span class="date">2 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-male success"></i> <b>Michael</b> commented on your link <span class="date">15 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-bug warning"></i> <b>Mia</b> commented on post <span class="date">30 minutes ago.</span></a></li>
                                                <li><a href="#"><i class="fa fa-credit-card danger"></i> <b>Andrew</b> sent you a request <span class="date">1 hour ago.</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <ul class="foot"><li><a href="#">View all activity </a></li></ul>
                                </li>
                            </ul>
                        </li>
                        <li class="button"><a class="toggle-menu menu-right push-body" href="javascript:;" class="speech-button"><i class="fa fa-comments"></i></a></li>
                    </ul>

                </div><!--/.nav-collapse animate-collapse -->
            </div>
        </div>


        <div class="cl-mcont">
            <?php echo $this->content; ?>
        </div>
    </div>

</div>

<!-- Right Chat-->
<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right side-chat">
    <div class="header">
        <h3>Chat</h3>
    </div>
    <div class="sub-header" href="#">
        <div class="icon"><i class="fa fa-user"></i></div> <p>Online (4)</p>
    </div>
    <div class="content">
        <p class="title">Family</p>
        <ul class="nav nav-pills nav-stacked contacts">
            <li class="online"><a href="#"><i class="fa fa-circle-o"></i> Michael Smith</a></li>
            <li class="online"><a href="#"><i class="fa fa-circle-o"></i> John Doe</a></li>
            <li class="online"><a href="#"><i class="fa fa-circle-o"></i> Richard Avedon</a></li>
            <li class="busy"><a href="#"><i class="fa fa-circle-o"></i> Allen Collins</a></li>
        </ul>

        <p class="title">Friends</p>
        <ul class="nav nav-pills nav-stacked contacts">
            <li class="online"><a href="#"><i class="fa fa-circle-o"></i> Jaime Garzon</a></li>
            <li class="outside"><a href="#"><i class="fa fa-circle-o"></i> Dave Grohl</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Victor Jara</a></li>
        </ul>

        <p class="title">Work</p>
        <ul class="nav nav-pills nav-stacked contacts">
            <li><a href="#"><i class="fa fa-circle-o"></i> Ansel Adams</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Gustavo Cerati</a></li>
        </ul>

    </div>
</nav>

<?php
    echo $this->headScript()
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.cookie/jquery.cookie.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.pushmenu/js/jPushMenu.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.nanoscroller/jquery.nanoscroller.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.sparkline/jquery.sparkline.min.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.ui/jquery-ui.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.gritter/js/jquery.gritter.js')
    ->appendFile($this->basePath() . '/assets/layout/js/behaviour/core.js');
    $this->headScript()->deleteContainer();

?>


<?php
        echo $this->headScript()
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.codemirror/lib/codemirror.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.codemirror/mode/xml/xml.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.codemirror/mode/css/css.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.codemirror/mode/htmlmixed/htmlmixed.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.codemirror/addon/edit/matchbrackets.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.vectormaps/jquery-jvectormap-1.2.2.min.js')
        ->appendFile($this->basePath() . '/assets/layout/js/jquery.vectormaps/maps/jquery-jvectormap-world-mill-en.js')
        ->appendFile($this->basePath() . '/assets/layout/js/behaviour/dashboard.js');
        $this->headScript()->deleteContainer();

?>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<?php
echo $this->headScript()
//    ->appendFile($this->basePath() . '/assets/layout/js/behaviour/voice-commands.js')
    ->appendFile($this->basePath() . '/assets/layout/js/bootstrap/dist/js/bootstrap.min.js')
    ->appendFile($this->basePath() . '/assets/layout/js/jquery.icheck/icheck.min.js')
    ->appendFile($this->basePath() . '/assets/layout/js/ckeditor/ckeditor.js')
    ->appendFile($this->basePath() . '/assets/layout/js/ckeditor/adapters/jquery.js')
    ->appendFile($this->basePath() . '/assets/layout/js/bootstrap.summernote/dist/summernote.min.js')
    ->appendFile($this->basePath() . '/assets/layout/js/bootstrap.wysihtml5/src/bootstrap-wysihtml5.js')
    ->appendFile($this->basePath() . '/assets/layout/js/dropzone/dropzone.js')
//    ->appendFile($this->basePath() . '/assets/layout/js/jquery.flot/jquery.flot.js')
//    ->appendFile($this->basePath() . '/assets/layout/js/jquery.flot/jquery.flot.pie.js')
//    ->appendFile($this->basePath() . '/assets/layout/js/jquery.flot/jquery.flot.resize.js')
//    ->appendFile($this->basePath() . '/assets/layout/js/jquery.flot/jquery.flot.labels.js')
//    ->appendFile($this->basePath() . '/assets/layout/js/jquery.select2/select2.min.js')
;
    $this->headScript()->deleteContainer();

?>
<script type="text/javascript">
    $(document).ready(function(){

        /*Input & Radio Buttons*/
        $('.icheck').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });

        $('label.tree-toggler').click(function () {
            var icon = $(this).children(".fa");
            if(icon.hasClass("fa-folder-o")){
                icon.removeClass("fa-folder-o").addClass("fa-folder-open-o");
            }else{
                icon.removeClass("fa-folder-open-o").addClass("fa-folder-o");
            }

            $(this).parent().children('ul.tree').toggle(300,function(){
                $(this).parent().toggleClass("open");
                $(".tree .nscroller").nanoScroller({ preventPageScrolling: true });
            });
        });
    });
</script>

</body>
</html>
